# Generated by Django 2.0.2 on 2018-02-22 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='club',
            options={'ordering': ('date_created',)},
        ),
    ]
